// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABbRNeT3_zKLq0rizZjsPafH5aRARGYsg',
    appId: '1:715225818619:web:07c863c8726899d173575e',
    messagingSenderId: '715225818619',
    projectId: 'assistant4u-52698',
    authDomain: 'assistant4u-52698.firebaseapp.com',
    storageBucket: 'assistant4u-52698.firebasestorage.app',
    measurementId: 'G-K8XWV591XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVkXQSjjLsCsxN-X-XzbzxDecmL9gOjjg',
    appId: '1:715225818619:android:1dc8e6a900c3596e73575e',
    messagingSenderId: '715225818619',
    projectId: 'assistant4u-52698',
    storageBucket: 'assistant4u-52698.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVu0awRjGHOZZXBDDQbofPBh9aqc9Xuh0',
    appId: '1:715225818619:ios:bdd74e9ca3f1d2c873575e',
    messagingSenderId: '715225818619',
    projectId: 'assistant4u-52698',
    storageBucket: 'assistant4u-52698.firebasestorage.app',
    iosBundleId: 'com.example.cspMobile',
  );
}
